### PR TITLE
Add first-year university maths

### PR DESCRIPTION
**Pull request by Mathmagician8191**
Saved for v1.1
Adds arctan/arcsin and hyperbolic trig
Will have vector-valued functions and partial derivatives

### CODE REVIEW

**Comment by MatthewLangisholdingmehostage** [comment]
It seems to be University level.
I can't do any of it but it seems good

**Comment by prefect69** [comment]
maybe add further years of study, ie... second year and third year univerity

**Comment by MatthewLangisholdingmehostage** [comment]
haha 69

**Comment by Mathmagician8191** [comment]
This will be merged now to avoid future merge conflicts, vector valued functions and partial derivatives will be added later when different question types are added

**Pull request merged**
