### PR TITLE
Use Katex rather than Mathjax for rendering

### PR DESCRIPTION
**Pull request by Mathmagician8191**
May improve performance
Renders quickly but question generation or simplification seems to be the performance issue
(preview button renders quickly but question generation is slow)

### CODE REVIEW

**Comment by MATTHEWmadeMEdoTHIS** [comment]
katex is better I think this is a good idea because it is more efficient then mathjax

**Comment by MATTHEWmadeMEdoTHIS** [comment]
I LIKE THIS

**Comment by MatthewLangisholdingmehostage** [comment]
Sometimes it is Faster but other times it takes 5x longer than before. so I don't know what is better

**Comment by Mathmagician8191** [comment]
I think its better than before, the best case is much better even if the worst case is the same

**Comment by MatthewLangisholdingmehostage** [comment]
ok

**Pull request merged**
