### PR TITLE
Added streak records

### LINKED ISSUE #39: A thing that tells you the Highest streak you have
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by Mathmagician8191**
Also fixed the enter mechanics, which were broken from integration merge.
Closes #39

### CODE REVIEW

**Comment by I-Love-Hentai** [comment]
thanks

**Comment by MatthewLangisholdingmehostage** [comment]
yes

**Comment by MatthewLangisholdingmehostage** [comment]
It worksd

**Comment by MatthewLangisholdingmehostage** [comment]
works

**Pull request merged**
