### PR TITLE
Add function minimum length

### PR DESCRIPTION
**Pull request by Mathmagician8191**
To try to prevent hard difficulty questions from being something like:
"Differentiate 4*x^2"
"Differentiate sin(x)"
More feedback is wanted about the questions.
More/less terms?
More/less chance of a function argument being another function?
Any more special functions?
Should weightings be changed?
More difficulty options/question types?

### CODE REVIEW

**Comment by MatthewLangisholdingmehostage** [comment]
yes

**Comment by I-Love-Hentai** [comment]
yeah

**Comment by MatthewLangisholdingmehostage** [comment]
yes

**Comment by MatthewLangisholdingmehostage** [comment]
it works

**Comment by I-Love-Hentai** [comment]
please do this is seems like a good idea
:) yeah

**Comment by I-Love-Hentai** [comment]
[e621.net/post](url)

**Comment by I-Love-Hentai** [comment]
### wow### 
this is funlky

**Comment by MatthewLangisholdingmehostage** [comment]
logng

**Comment by MatthewLangisholdingmehostage** [comment]
long

**Comment by MatthewLangisholdingmehostage** [comment]
long

**Comment by MatthewLangisholdingmehostage** [comment]
haha

**Comment by MatthewLangisholdingmehostage** [comment]
### ### ### ### ### ### ### ### BOOMER

**Comment by MatthewLangisholdingmehostage** [comment]
yimyum

**Comment by MatthewLangisholdingmehostage** [comment]
it good

**Pull request merged**
