### PR TITLE
Add function reference page

### LINKED ISSUE #9: Place to learn
Another issue is that I believe that there should be a place to learn firstly and then get these questions.

### PR DESCRIPTION
**Pull request by Mathmagician8191**
Closes #9

### CODE REVIEW

**Comment by MatthewLangisholdingmehostage** [comment]
It needs an Explanation as I have no clue what these mean or when I should use them.

**Comment by MatthewLangisholdingmehostage** [comment]
I also cannot get back to the main page from new page

**Comment by MatthewLangisholdingmehostage** [comment]
I am stuck in the void and cannot return to calculus

**Comment by Mathmagician8191** [comment]
What about making the function reference on the same page as the regular game to give the space a use?

**Pull request merged**
