### PR TITLE
Fix issues with correct answer detection (hopefully)

### LINKED ISSUE #20: It doesn't recognise that the correct answer is the same as the players answer
Capture
Captures
Even if both answers are Identical (As seen Above) the website sees them as different and wrong answers.

### PR DESCRIPTION
**Pull request by Mathmagician8191**
Closes #20

### CODE REVIEW

**Comment by MatthewLangisholdingmehostage** [comment]
It still doesn't work
Capture

**Comment by MatthewLangisholdingmehostage** [comment]
Capture
Capture2

**Comment by MatthewLangisholdingmehostage** [comment]
w

**Comment by MatthewLangisholdingmehostage** [comment]
f

**Comment by MatthewLangisholdingmehostage** [comment]
v

**Comment by Mathmagician8191** [comment]
The changes had not registered for some reason, should be fixed now

**Comment by MatthewLangisholdingmehostage** [comment]
It seems to be working now

**Pull request merged**
