### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by Mathmagician8191**

### CODE REVIEW

**Comment by MatthewLangisholdingmehostage** [comment]
It works well, however it should tell you that you need to include 'c' as the constant

**Comment by MatthewLangisholdingmehostage** [comment]
calculating the constant

**Comment by Mathmagician8191** [comment]
Is that fine?

**Comment by Mathmagician8191** [comment]
Closes #23

**Comment by MatthewLangisholdingmehostage** [comment]
It is fine

**Pull request merged**
