### PR TITLE
Make enter preview instead of submit

### PR DESCRIPTION
**Pull request by Mathmagician8191**
To prevent accidentally entering the answer before you are ready

EDIT:
The preview mechanics have changed.
When you press enter, the page keeps track of the last thing in the textbox.
If it matches the current contents, it submits, otherwise it previews and updates the copy of the textbox contents.

### CODE REVIEW

**Comment by I-Love-Hentai** [comment]
maybe have the enter key open a prompt that asks if they are sure they want to submit? pressing etner again submits

**Comment by Mathmagician8191** [comment]
Would there be a key to cancel submission?

**Comment by I-Love-Hentai** [comment]
> Would there be a key to cancel submission?

ESC, probably :)

**Comment by Mathmagician8191** [comment]
What about a key to preview?
You will usually want to preview before submitting.
Maybe enter once to preview, enter again without changes to submit?

**Comment by I-Love-Hentai** [comment]
> What about a key to preview?
> You will usually want to preview before submitting.
> Maybe enter once to preview, enter again without changes to submit?

yes this sounds good do this one please yes mhmm yeah ok mhmm yeah yeah mhmm yeah

**Comment by Gayrelationships** [comment]
this a good idea and I have never committed tax fraud

**Comment by Gayrelationships** [comment]
i have 36 child

**Comment by Gayrelationships** [comment]
mmm i love gay poren and penis in my ass yuj yum please guvbe cok

**Comment by Gayrelationships** [comment]
please write more information in the pull requests

**Pull request merged**
